FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

COPY /ic_model_api/ /api/
COPY requirements.ic-model.txt /api/requirements.txt

WORKDIR /api

RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]